sonar.projectKey=tingeso-frontend
sonar.projectName=Frontend - Sistema de Préstamos
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.login=sqa_82acc078d44efd6a8f4ad7029b85f5187e96ca80

sonar.javascript.environments=browser

sonar.exclusions=node_modules/**, build/**, dist/**, src/**/*.test.js, src/**/*.test.jsx, src/setupTests.js