spring.application.name=ProyectoTingeso

logging.level.com.example.ProyectoTingeso.Backend.Services=DEBUG


# Base de datos - Funciona en Docker (con variables) y Local (con defaults)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ProyectTingeso}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:09282325}
server.port=8090

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= create-drop
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Keycloak - Conecta a localhost (funciona para desarrollo local)
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/sisgr-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/sisgr-realm/protocol/openid-connect/certs